void furusato(){
    ledcWriteTone(1,C4);//ド
    delay(BEAT);
    ledcWriteTone(1,C4);//ド
    delay(BEAT);
    ledcWriteTone(1,C4);//ド
    delay(BEAT);
    ledcWriteTone(1,D4);//レ
    delay(1000);
    ledcWriteTone(1,E4);//ミ
    delay(BEAT);
    ledcWriteTone(1,D4);//レ
    delay(BEAT);
    ledcWriteTone(1,E4);//ミ
    delay(BEAT);
    ledcWriteTone(1,E4);//ミ
    delay(BEAT);
    ledcWriteTone(1,F4);//ファ
    delay(BEAT);
    ledcWriteTone(1,G4);//ソ
    delay(1000);
    ledcWriteTone(1,F4);//ファ
    delay(BEAT);
    ledcWriteTone(1,G4);//ソ
    delay(BEAT);
    ledcWriteTone(1,A4);//ラ
    delay(BEAT);
    ledcWriteTone(1,E4);//ミ
    delay(BEAT);
    ledcWriteTone(1,F4);//ファ
    delay(BEAT);
    ledcWriteTone(1,E4);//ミ
    delay(BEAT);
    ledcWriteTone(1,D4);//レ
    delay(BEAT);
    ledcWriteTone(1,D4);//レ
    delay(BEAT);
    ledcWriteTone(1,B3);//シ
    delay(BEAT);
    ledcWriteTone(1,C4);//ド
    delay(BEAT);
    ledcWriteTone(0.5,C4);//ド
    delay(BEAT);
    ledcWriteTone(1,R0);//
    delay(1000);
}
void rondon(){
  ledcWriteTone(1,G4);//ソ
    delay(BEAT);
  ledcWriteTone(1,A4);//ラ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(600);
  ledcWriteTone(1,R0);//休符
    delay(BEAT);
  ledcWriteTone(1,D4);//レ
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(550);
  ledcWriteTone(1,R0);//休符
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(BEAT);
  ledcWriteTone(1,R0);//休符
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(BEAT);
  ledcWriteTone(1,A4);//ラ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(600);
  ledcWriteTone(1,R0);//休符
    delay(BEAT);
  ledcWriteTone(1,D4);//レ
    delay(1000);
  ledcWriteTone(1,G4);//ソ
    delay(1000);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,C4);//ド
    delay(1000);
  ledcWriteTone(1,R0);//休符
    delay(1000);
  }
void seijya (){
  ledcWriteTone(1,C4);//ド
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(2000);
  ledcWriteTone(1,C4);//ド
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(2000);
   ledcWriteTone(1,C4);//ド
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(1000);
  ledcWriteTone(1,E4);//ミ
    delay(1000);
  ledcWriteTone(1,C4);//ド
    delay(1000);
  ledcWriteTone(1,E4);//ミ
    delay(1000);
  ledcWriteTone(1,D4);//レ
    delay(2500);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,D4);//レ
    delay(BEAT);
  ledcWriteTone(1,C4);//ド
    delay(1500);
  ledcWriteTone(1,C4);//ド
    delay(BEAT);
  ledcWriteTone(1,E4);//ミ
    delay(1000);
  ledcWriteTone(1,G4);//ソ
    delay(1000);
  ledcWriteTone(1,G4);//ソ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(2000);
  ledcWriteTone(1,E4);//ミ
    delay(BEAT);
  ledcWriteTone(1,F4);//ファ
    delay(BEAT);
  ledcWriteTone(1,G4);//ソ
    delay(1000);
  ledcWriteTone(1,E4);//ミ
    delay(1000);
  ledcWriteTone(1,C4);//ド
    delay(1000);
  ledcWriteTone(1,D4);//レ
    delay(1000);
  ledcWriteTone(1,C4);//ド
    delay(2500);
  ledcWriteTone(1,R0);//休符
    delay(BEAT);
  }
